# -*- coding: utf-8 -*-
"""modelling_tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CcCJ3JxWGv4QvYaibgHnIgeAaojSN_pA
"""

!pip install mlflow dagshub

# modelling_tuning.py
import pandas as pd
import numpy as np
import mlflow
import mlflow.sklearn
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report, roc_auc_score
)

# Setup MLflow Tracking ke DagsHub
import dagshub
dagshub.init(
    repo_owner='fathorrosi1',
    repo_name='Eksperimen_SML_Mohammad_Fathorrosi',
    mlflow=True
)

mlflow.set_experiment('Telco_Churn_Tuning')

# Load Data
DATA_PATH = 'namadataset_preprocessing/telco_churn_preprocessing.csv'
df = pd.read_csv(DATA_PATH)

X = df.drop(columns=['Churn'])
y = df['Churn']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Hyperparameter Tuning dengan GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [5, 10, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

base_model = RandomForestClassifier(random_state=42, class_weight='balanced')

grid_search = GridSearchCV(
    estimator=base_model,
    param_grid=param_grid,
    cv=3,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Training + Manual Logging ke MLflow
with mlflow.start_run(run_name='rf_tuning_manual_logging'):

    # Fit GridSearch
    grid_search.fit(X_train, y_train)
    best_model = grid_search.best_estimator_

    # Prediksi
    y_pred = best_model.predict(X_test)
    y_proba = best_model.predict_proba(X_test)[:, 1]

    # Hitung metrik
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, y_proba)

    # MANUAL LOGGING — Params
    mlflow.log_params(grid_search.best_params_)
    mlflow.log_param('model_type', 'RandomForestClassifier')
    mlflow.log_param('class_weight', 'balanced')
    mlflow.log_param('cv_folds', 3)
    mlflow.log_param('scoring', 'f1')

    # MANUAL LOGGING — Metrics (sama dengan autolog)
    mlflow.log_metric('accuracy', acc)
    mlflow.log_metric('precision', prec)
    mlflow.log_metric('recall', rec)
    mlflow.log_metric('f1_score', f1)
    mlflow.log_metric('roc_auc', roc_auc)
    mlflow.log_metric('best_cv_score', grid_search.best_score_)

    print(f"Accuracy : {acc:.4f}")
    print(f"Precision: {prec:.4f}")
    print(f"Recall   : {rec:.4f}")
    print(f"F1 Score : {f1:.4f}")
    print(f"ROC AUC  : {roc_auc:.4f}")

    # ARTEFAK TAMBAHAN 1: Confusion Matrix
    plt.figure(figsize=(6, 5))
    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['No Churn', 'Churn'],
                yticklabels=['No Churn', 'Churn'])
    plt.title('Confusion Matrix — Random Forest Tuning')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.tight_layout()
    plt.savefig('confusion_matrix.png')
    plt.close()
    mlflow.log_artifact('confusion_matrix.png', artifact_path='evaluation')

    # ARTEFAK TAMBAHAN 2: Feature Importance
    plt.figure(figsize=(10, 8))
    importances = pd.Series(
        best_model.feature_importances_,
        index=X.columns
    ).sort_values(ascending=True).tail(15)

    importances.plot(kind='barh', color='steelblue')
    plt.title('Top 15 Feature Importance')
    plt.xlabel('Importance')
    plt.tight_layout()
    plt.savefig('feature_importance.png')
    plt.close()
    mlflow.log_artifact('feature_importance.png', artifact_path='evaluation')

    # ARTEFAK TAMBAHAN 3: Classification Report (txt)
    report = classification_report(y_test, y_pred, target_names=['No Churn', 'Churn'])
    with open('classification_report.txt', 'w') as f:
        f.write(report)
    mlflow.log_artifact('classification_report.txt', artifact_path='evaluation')

    # LOG MODEL
    mlflow.sklearn.log_model(
    sk_model=best_model,
    artifact_path='model',
    registered_model_name='telco_churn_rf_tuning',
    skops_trusted_types=['sklearn.tree._tree.Tree']
)

    print("\nRun selesai! Cek DagsHub untuk melihat hasilnya.")