# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y8z_cIa0oqIbAeTmj7-hfsxOvdK7LieJ
"""

!pip install mlflow dagshub

# modelling.py
import pandas as pd
import numpy as np
import mlflow
import mlflow.sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Setup MLflow Tracking ke DagsHub
import dagshub
dagshub.init(
    repo_owner='fathorrosi1',
    repo_name='Eksperimen_SML_Mohammad_Fathorrosi',
    mlflow=True
)

# Load Data
DATA_PATH = 'namadataset_preprocessing/telco_churn_preprocessing.csv'
df = pd.read_csv(DATA_PATH)

X = df.drop(columns=['Churn'])
y = df['Churn']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Training dengan Autolog
mlflow.sklearn.autolog()

with mlflow.start_run(run_name='baseline_autolog'):
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"Accuracy: {acc:.4f}")